const GENRES=["Akční","Animovaný","Dobrodružný","Dokument","Drama","Fantasy","Historický","Horor","Hudební","Komedie","Krimi","Mysteriózní","Rodinný","Romantika","Sci-fi","Thriller","Válečný","Western"];
const cfg=window.MOVIENIGHT_CONFIG||{};
const cloud=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey);
const tmdbReady=Boolean(cfg.tmdbReadToken);
const db=cloud?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
let items=[],activeType="movie",picked=null,selectedTmdb=null,searchTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=message=>{const el=$("#toast");el.textContent=message;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),2600)};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function normalize(row){return{...row,seen_kuba:Boolean(row.seen_kuba),seen_partner:Boolean(row.seen_partner),favorite:Boolean(row.favorite)}}
async function load(){if(cloud){const{data,error}=await db.from("titles").select("*").order("created_at",{ascending:false});if(error)return toast("Nepodařilo se načíst databázi. Spusť aktuální supabase.sql.");items=(data||[]).map(normalize)}else items=JSON.parse(localStorage.getItem("movienight_titles")||"[]");updateGenres();render()}
function saveLocal(){localStorage.setItem("movienight_titles",JSON.stringify(items))}
async function createTitle(value){if(cloud){const{data,error}=await db.from("titles").insert(value).select().single();if(error)return toast(error.code==="23505"?"Tento titul už v seznamu je.":"Titul se nepodařilo uložit. Spusť aktuální SQL.");items.unshift(normalize(data))}else{items.unshift({...value,id:crypto.randomUUID(),created_at:new Date().toISOString()});saveLocal()}updateGenres();render();toast(value.type==="movie"?"Film byl přidán.":"Seriál byl přidán.");closeModal()}
async function patchTitle(id,changes){items=items.map(x=>x.id===id?{...x,...changes}:x);render();if(cloud){const{error}=await db.from("titles").update(changes).eq("id",id);if(error){toast("Změnu se nepodařilo uložit.");load()}}else saveLocal()}
async function deleteTitle(id){if(!confirm("Opravdu odstranit titul ze seznamu?"))return;if(cloud){const{error}=await db.from("titles").delete().eq("id",id);if(error)return toast("Titul se nepodařilo odstranit.")}items=items.filter(x=>x.id!==id);saveLocal();render();toast("Titul byl odstraněn.")}
function eligible(){const genre=$("#genre").value,seen=$("#seen").value,duration=$("#duration").value;return items.filter(x=>x.type===activeType&&(genre==="Všechny"||x.genre===genre||x.genre_secondary===genre)&&(seen!=="nobody"||(!x.seen_kuba&&!x.seen_partner))&&(seen!=="kuba"||!x.seen_kuba)&&(seen!=="partner"||!x.seen_partner)&&(seen!=="not-both"||!(x.seen_kuba&&x.seen_partner))&&(activeType==="series"||duration==="any"||Number(x.runtime||999)<=Number(duration)))}
function filteredLibrary(){const q=$("#search").value.toLowerCase(),filter=$("#library-filter").value,genre=$("#library-genre").value,sort=$("#library-sort").value;const list=items.filter(x=>x.type===activeType&&(x.title+" "+(x.original_title||"")+" "+x.genre+" "+(x.genre_secondary||"")+" "+(x.platform||"")).toLowerCase().includes(q)&&(genre==="Všechny"||x.genre===genre||x.genre_secondary===genre)&&(filter!=="unseen"||!(x.seen_kuba&&x.seen_partner))&&(filter!=="favorites"||x.favorite));return list.sort((a,b)=>{if(sort==="rating-desc")return Number(b.vote_average??-1)-Number(a.vote_average??-1);if(sort==="rating-asc"){if(a.vote_average==null)return 1;if(b.vote_average==null)return-1;return Number(a.vote_average)-Number(b.vote_average)}if(sort==="title-asc")return a.title.localeCompare(b.title,"cs");return new Date(b.created_at||0)-new Date(a.created_at||0)})}
function updateGenres(){const all=[...new Set([...GENRES,...items.flatMap(x=>[x.genre,x.genre_secondary]).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,"cs"));const current=$("#genre").value;$("#genre").innerHTML='<option>Všechny</option>'+all.map(g=>'<option>'+esc(g)+'</option>').join("");if(all.includes(current))$("#genre").value=current;const libraryCurrent=$("#library-genre").value;$("#library-genre").innerHTML='<option value="Všechny">Všechny žánry</option>'+all.map(g=>'<option>'+esc(g)+'</option>').join("");if(all.includes(libraryCurrent))$("#library-genre").value=libraryCurrent;$('[name="genre"]').innerHTML=all.map(g=>'<option>'+esc(g)+'</option>').join("");$('[name="genre_secondary"]').innerHTML='<option value="">Bez druhého žánru</option>'+all.map(g=>'<option>'+esc(g)+'</option>').join("")}
function card(x){const meta=x.type==="series"?[x.year,x.seasons&&x.seasons+" řad",x.platform,x.vote_average&&"★ "+Number(x.vote_average).toFixed(1)]:[x.year,x.runtime&&x.runtime+" min",x.platform,x.vote_average&&"★ "+Number(x.vote_average).toFixed(1)];const poster=x.poster_path?' style="background-image:linear-gradient(0deg,#111 0,transparent 65%),url(https://image.tmdb.org/t/p/w500'+esc(x.poster_path)+')"':"";return '<article class="card"><div class="poster p'+(String(x.id).charCodeAt(0)%5)+'"'+poster+'><span>'+(x.type==="movie"?"FILM":"SERIÁL")+' · '+esc([x.genre,x.genre_secondary].filter(Boolean).join(" · "))+'</span>'+(x.poster_path?"":'<strong>'+esc(x.title[0])+'</strong>')+'<button class="heart '+(x.favorite?"on":"")+'" data-action="favorite" data-id="'+x.id+'">♥</button></div><div class="body"><div class="title"><div><h3>'+esc(x.title)+'</h3>'+(x.original_title&&x.original_title.toLocaleLowerCase()!==x.title.toLocaleLowerCase()?'<span class="original-title">'+esc(x.original_title)+'</span>':'')+'<p>'+meta.filter(Boolean).map(esc).join(" · ")+'</p></div><button class="delete" data-action="delete" data-id="'+x.id+'">×</button></div>'+(x.overview?'<p class="overview">'+esc(x.overview)+'</p>':"")+(x.note?'<blockquote>„'+esc(x.note)+'“</blockquote>':"")+'<div class="seen-buttons"><button class="'+(x.seen_kuba?"yes":"")+'" data-action="kuba" data-id="'+x.id+'"><i>'+(x.seen_kuba?"✓":"")+'</i>Kuba</button><button class="'+(x.seen_partner?"yes":"")+'" data-action="partner" data-id="'+x.id+'"><i>'+(x.seen_partner?"✓":"")+'</i>Iry</button></div></div></article>'}
function render(){const pool=eligible(),list=filteredLibrary(),typeItems=items.filter(x=>x.type===activeType),both=typeItems.filter(x=>x.seen_kuba&&x.seen_partner).length;$("#pool").textContent=pool.length;$("#draw").disabled=!pool.length;$(".no-match").classList.toggle("hidden",Boolean(pool.length)||!typeItems.length);$("#total").textContent=typeItems.length;$("#remaining").textContent=typeItems.length-both;$("#together").textContent=both;$("#count").textContent=list.length+" titulů";$("#items").innerHTML=list.map(card).join("");$("#items").classList.toggle("hidden",!list.length);$("#empty").classList.toggle("hidden",Boolean(list.length));$("#library-title").textContent=activeType==="movie"?"Naše filmy":"Naše seriály";$("#draw").textContent=activeType==="movie"?"✦ Vylosovat film":"✦ Vylosovat seriál";$("#duration-label").classList.toggle("hidden",activeType==="series")}
function switchType(type){activeType=type;picked=null;$("#winner").classList.add("hidden");$$(".type-switch button,.collection-switch button").forEach(b=>b.classList.toggle("active",b.dataset.type===type));$$(".nav-tab").forEach(b=>b.classList.toggle("active",b.dataset.view===(type==="movie"?"movies":"series")));render()}
function draw(){const pool=eligible();if(!pool.length)return;let n=0;$("#draw").disabled=true;const timer=setInterval(()=>{picked=pool[Math.floor(Math.random()*pool.length)];showWinner(true);if(++n===10){clearInterval(timer);showWinner(false);$("#draw").disabled=false}},90)}
function showWinner(rolling){const w=$("#winner");w.classList.remove("hidden");w.innerHTML='<div><small>'+(rolling?"LOSOVÁNÍ…":"DNES VEČER VYHRÁVÁ")+'</small><h2>'+esc(picked.title)+'</h2>'+(picked.original_title&&picked.original_title.toLocaleLowerCase()!==picked.title.toLocaleLowerCase()?'<span class="winner-original">'+esc(picked.original_title)+'</span>':'')+'<p>'+[picked.year,[picked.genre,picked.genre_secondary].filter(Boolean).join(" · "),picked.type==="series"?(picked.seasons?picked.seasons+" řad":null):(picked.runtime?picked.runtime+" min":null),picked.platform].filter(Boolean).map(esc).join(" · ")+'</p></div>'+(rolling?"":'<button id="again">↻ Jiný titul</button>');if(!rolling)$("#again").onclick=draw}
async function tmdbFetch(path){const response=await fetch("https://api.themoviedb.org/3"+path,{headers:{Authorization:"Bearer "+cfg.tmdbReadToken,accept:"application/json"}});if(!response.ok)throw new Error("TMDb "+response.status);return response.json()}
async function searchTmdb(query){const box=$("#tmdb-results");if(!tmdbReady||query.trim().length<2){box.classList.add("hidden");return}box.innerHTML='<div class="tmdb-loading">Vyhledávám v TMDb…</div>';box.classList.remove("hidden");try{const endpoint=$('[name="type"]:checked').value==="movie"?"movie":"tv";const data=await tmdbFetch("/search/"+endpoint+"?language=cs-CZ&include_adult=false&query="+encodeURIComponent(query));const results=(data.results||[]).slice(0,6);box.innerHTML=results.length?results.map(x=>{const title=x.title||x.name,original=x.original_title||x.original_name||"",date=x.release_date||x.first_air_date||"",img=x.poster_path?"https://image.tmdb.org/t/p/w92"+x.poster_path:"";return '<button type="button" class="tmdb-result" data-tmdb-id="'+x.id+'">'+(img?'<img src="'+img+'" alt="">':'<span></span>')+'<span><b>'+esc(title)+'</b>'+(original&&original.toLocaleLowerCase()!==title.toLocaleLowerCase()?'<span class="tmdb-original">'+esc(original)+'</span>':'')+'<span>'+esc(date.slice(0,4))+' · '+(endpoint==="movie"?"Film":"Seriál")+'</span></span></button>'}).join(""):'<div class="tmdb-loading">Nic jsme nenašli. Titul můžeš vyplnit ručně.</div>'}catch{box.innerHTML='<div class="tmdb-loading">TMDb nyní neodpovídá. Titul můžeš vyplnit ručně.</div>'}}
function setOption(name,value){if(!value)return;const select=$('[name="'+name+'"]');if(![...select.options].some(o=>o.value===value))select.add(new Option(value,value));select.value=value}
async function selectTmdb(id){const type=$('[name="type"]:checked').value;try{const endpoint=type==="movie"?"movie":"tv";const x=await tmdbFetch("/"+endpoint+"/"+id+"?language=cs-CZ");selectedTmdb=x;$('[name="title"]').value=x.title||x.name||"";$('[name="year"]').value=(x.release_date||x.first_air_date||"").slice(0,4);$('[name="runtime"]').value=type==="movie"?(x.runtime||""):"";$('[name="seasons"]').value=type==="series"?(x.number_of_seasons||""):"";$('[name="overview"]').value=x.overview||"";setOption("genre",x.genres?.[0]?.name);setOption("genre_secondary",x.genres?.[1]?.name);$("#tmdb-results").classList.add("hidden");toast("Údaje byly načteny z TMDb.")}catch{toast("Detail titulu se nepodařilo načíst.")}}
function openModal(){selectedTmdb=null;$("#modal").classList.remove("hidden");$('[name="type"][value="'+activeType+'"]').checked=true;setTimeout(()=>$('[name="title"]').focus(),50)}
function closeModal(){selectedTmdb=null;$("#modal").classList.add("hidden");$("#tmdb-results").classList.add("hidden");$("#form").reset()}
$$(".add").forEach(b=>b.onclick=openModal);$(".close").onclick=closeModal;$("#modal").onmousedown=e=>{if(e.target===e.currentTarget)closeModal()};$$(".type-switch button,.collection-switch button").forEach(b=>b.onclick=()=>switchType(b.dataset.type));$$(".nav-tab").forEach(b=>b.onclick=()=>{switchType(b.dataset.view==="movies"?"movie":"series");$("#library").scrollIntoView()});
["genre","seen","duration","library-filter","library-genre","library-sort"].forEach(id=>$("#"+id).onchange=render);$("#search").oninput=render;$("#draw").onclick=draw;
$('[name="title"]').oninput=e=>{selectedTmdb=null;clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchTmdb(e.target.value),300)};
$("#tmdb-results").onclick=e=>{const button=e.target.closest("[data-tmdb-id]");if(button)selectTmdb(button.dataset.tmdbId)};
$$('[name="type"]').forEach(r=>r.onchange=()=>{selectedTmdb=null;$("#tmdb-results").classList.add("hidden");$('[name="title"]').value="";$('[name="runtime"]').closest("label").classList.toggle("hidden",r.value==="series"&&r.checked);$('[name="seasons"]').closest("label").classList.toggle("hidden",r.value==="movie"&&r.checked)});
$("#form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),type=f.get("type");await createTitle({type,title:String(f.get("title")).trim(),genre:f.get("genre"),genre_secondary:f.get("genre_secondary")||null,year:f.get("year")?Number(f.get("year")):null,runtime:type==="movie"&&f.get("runtime")?Number(f.get("runtime")):null,seasons:type==="series"&&f.get("seasons")?Number(f.get("seasons")):null,platform:String(f.get("platform")||"").trim(),status:f.get("status"),overview:String(f.get("overview")||"").trim(),note:String(f.get("note")||"").trim(),seen_kuba:f.get("seen_kuba")==="on",seen_partner:f.get("seen_partner")==="on",favorite:false,tmdb_id:selectedTmdb?.id||null,original_title:selectedTmdb?.original_title||selectedTmdb?.original_name||null,poster_path:selectedTmdb?.poster_path||null,vote_average:selectedTmdb?.vote_average||null})};
$("#items").onclick=e=>{const b=e.target.closest("[data-action]");if(!b)return;const x=items.find(i=>String(i.id)===b.dataset.id);if(!x)return;if(b.dataset.action==="delete")deleteTitle(x.id);if(b.dataset.action==="favorite")patchTitle(x.id,{favorite:!x.favorite});if(b.dataset.action==="kuba")patchTitle(x.id,{seen_kuba:!x.seen_kuba});if(b.dataset.action==="partner")patchTitle(x.id,{seen_partner:!x.seen_partner})};
updateGenres();load();if(cloud)db.channel("titles-live").on("postgres_changes",{event:"*",schema:"public",table:"titles"},()=>load()).subscribe();