const GENRES=["Akční","Animovaný","Dobrodružný","Dokument","Drama","Fantasy","Historický","Horor","Hudební","Komedie","Krimi","Mysteriózní","Rodinný","Romantika","Sci-fi","Thriller","Válečný","Western"];
const cfg=window.MOVIENIGHT_CONFIG||{};
const cloud=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey);
const tmdbReady=Boolean(cfg.tmdbReadToken);
const db=cloud?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
let items=[],historyItems=[],activeType="movie",picked=null,selectedTmdb=null,searchTimer=null,drawInProgress=false,drawRun=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=message=>{const el=$("#toast");el.textContent=message;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),2600)};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function normalize(row){return{...row,seen_kuba:Boolean(row.seen_kuba),seen_partner:Boolean(row.seen_partner),favorite:Boolean(row.favorite),collection_checked:Boolean(row.collection_checked)}}
async function load(){if(cloud){const{data,error}=await db.from("titles").select("*").order("created_at",{ascending:false});if(error){items=JSON.parse(localStorage.getItem("movienight_cloud_cache")||"[]").map(normalize);toast(items.length?"Databáze je offline. Zobrazuji poslední uložená data.":"Nepodařilo se načíst databázi. Spusť aktuální supabase.sql.")}else items=(data||[]).map(normalize)}else items=JSON.parse(localStorage.getItem("movienight_titles")||"[]").map(normalize);if(cloud&&items.length)localStorage.setItem("movienight_cloud_cache",JSON.stringify(items));updateGenres();updatePlatforms();render();loadHistory();backfillCollections()}

async function loadHistory(){if(cloud){const{data,error}=await db.from("draw_history").select("*").order("chosen_at",{ascending:false}).limit(100);if(error){historyItems=JSON.parse(localStorage.getItem("movienight_history")||"[]")}else historyItems=data||[]}else historyItems=JSON.parse(localStorage.getItem("movienight_history")||"[]");saveHistoryLocal();renderHistory();render()}
async function acceptPick(){if(!picked)return;const entry={title_id:picked.id,title_snapshot:picked.title,type:picked.type,poster_path:picked.poster_path||null,watched:false};if(cloud){const{data,error}=await db.from("draw_history").insert(entry).select().single();if(error)return toast("Historii se nepodařilo uložit. Spusť aktuální supabase.sql.");historyItems.unshift(data)}else historyItems.unshift({...entry,id:crypto.randomUUID(),chosen_at:new Date().toISOString()});saveHistoryLocal();showWinner();closeRoulette();renderHistory();render();$("#winner").scrollIntoView({behavior:"smooth",block:"center"})}
async function updateHistory(id,changes){historyItems=historyItems.map(x=>x.id===id?{...x,...changes}:x);saveHistoryLocal();renderHistory();render();if(cloud){const{error}=await db.from("draw_history").update(changes).eq("id",id);if(error){toast("Historii se nepodařilo upravit.");loadHistory()}}}
async function removeHistory(id){if(cloud){const{error}=await db.from("draw_history").delete().eq("id",id);if(error)return toast("Záznam se nepodařilo odstranit.")}historyItems=historyItems.filter(x=>x.id!==id);saveHistoryLocal();renderHistory();render()}
function renderHistory(){const box=$("#history-items");if(!box)return;box.innerHTML=historyItems.slice(0,12).map(h=>{const date=new Intl.DateTimeFormat("cs-CZ",{day:"numeric",month:"short",year:"numeric"}).format(new Date(h.chosen_at));const poster=h.poster_path?' style="background-image:url(https://image.tmdb.org/t/p/w185'+esc(h.poster_path)+')"':"";return '<article class="history-card"><span class="history-poster"'+poster+'></span><div><small>'+esc(h.type==="movie"?"FILM":"SERIÁL")+'</small><h3>'+esc(h.title_snapshot)+'</h3><span>'+esc(date)+'</span></div><div class="history-actions"><button data-history="watched" data-id="'+h.id+'" class="'+(h.watched?"done":"")+'">'+(h.watched?"✓ Viděno":"Označit jako viděné")+'</button><button data-history="delete" data-id="'+h.id+'" aria-label="Odstranit">×</button></div></article>'}).join("");$("#history-empty").classList.toggle("hidden",Boolean(historyItems.length));box.classList.toggle("hidden",!historyItems.length)}

let backfillRunning=false;
async function backfillCollections(){if(!tmdbReady||backfillRunning)return;const pending=items.filter(x=>x.type==="movie"&&x.tmdb_id&&!x.collection_checked).slice(0,30);if(!pending.length)return;backfillRunning=true;let schemaError=false;await Promise.all(pending.map(async item=>{try{const detail=await tmdbFetch("/movie/"+item.tmdb_id+"?language=cs-CZ");const collection=detail.belongs_to_collection;const changes={collection_id:collection?.id||null,collection_name:collection?.name||null,collection_poster_path:collection?.poster_path||null,collection_checked:true};if(cloud){const{error}=await db.from("titles").update(changes).eq("id",item.id);if(error){schemaError=true;return}}Object.assign(item,changes)}catch{}}));if(!cloud)saveLocal();backfillRunning=false;render();if(schemaError)toast("Pro filmové série spusť aktuální supabase.sql.")}
function saveLocal(){localStorage.setItem("movienight_titles",JSON.stringify(items))}
function saveHistoryLocal(){localStorage.setItem("movienight_history",JSON.stringify(historyItems))}
async function createTitle(value){if(cloud){const{data,error}=await db.from("titles").insert(value).select().single();if(error)return toast(error.code==="23505"?"Tento titul už v seznamu je.":"Titul se nepodařilo uložit. Spusť aktuální SQL.");items.unshift(normalize(data))}else{items.unshift({...value,id:crypto.randomUUID(),created_at:new Date().toISOString()});saveLocal()}updateGenres();render();toast(value.type==="movie"?"Film byl přidán.":"Seriál byl přidán.");closeModal()}
async function patchTitle(id,changes){items=items.map(x=>x.id===id?{...x,...changes}:x);render();if(cloud){const{error}=await db.from("titles").update(changes).eq("id",id);if(error){toast("Změnu se nepodařilo uložit.");load()}}else saveLocal()}
async function deleteTitle(id){if(!confirm("Opravdu odstranit titul ze seznamu?"))return;if(cloud){const{error}=await db.from("titles").delete().eq("id",id);if(error)return toast("Titul se nepodařilo odstranit.")}items=items.filter(x=>x.id!==id);saveLocal();render();toast("Titul byl odstraněn.")}
function eligible(){const genre=$("#genre").value,seen=$("#seen").value,duration=$("#duration").value,platform=$("#draw-platform").value,avoid=$("#avoid-recent").checked,cutoff=Date.now()-30*864e5,recent=new Set(historyItems.filter(h=>new Date(h.chosen_at).getTime()>=cutoff).map(h=>String(h.title_id)));return items.filter(x=>x.type===activeType&&(genre==="Všechny"||x.genre===genre||x.genre_secondary===genre)&&(platform==="any"||x.platform===platform)&&(seen!=="nobody"||(!x.seen_kuba&&!x.seen_partner))&&(seen!=="kuba"||!x.seen_kuba)&&(seen!=="partner"||!x.seen_partner)&&(seen!=="not-both"||!(x.seen_kuba&&x.seen_partner))&&(!avoid||!recent.has(String(x.id)))&&(activeType==="series"||duration==="any"||Number(x.runtime||999)<=Number(duration)))}
function filteredLibrary(){const q=$("#search").value.toLowerCase(),filter=$("#library-filter").value,genre=$("#library-genre").value,sort=$("#library-sort").value;const list=items.filter(x=>x.type===activeType&&(x.title+" "+(x.original_title||"")+" "+(x.collection_name||"")+" "+x.genre+" "+(x.genre_secondary||"")+" "+(x.platform||"")).toLowerCase().includes(q)&&(genre==="Všechny"||x.genre===genre||x.genre_secondary===genre)&&(filter!=="unseen"||!(x.seen_kuba&&x.seen_partner))&&(filter!=="favorites"||x.favorite));return list.sort((a,b)=>{if(sort==="rating-desc")return Number(b.vote_average??-1)-Number(a.vote_average??-1);if(sort==="rating-asc"){if(a.vote_average==null)return 1;if(b.vote_average==null)return-1;return Number(a.vote_average)-Number(b.vote_average)}if(sort==="our-rating-desc")return (ownRating(b)??-1)-(ownRating(a)??-1);if(sort==="title-asc")return a.title.localeCompare(b.title,"cs");return new Date(b.created_at||0)-new Date(a.created_at||0)})}
function updateGenres(){const all=[...new Set([...GENRES,...items.flatMap(x=>[x.genre,x.genre_secondary]).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,"cs"));const current=$("#genre").value;$("#genre").innerHTML='<option>Všechny</option>'+all.map(g=>'<option>'+esc(g)+'</option>').join("");if(all.includes(current))$("#genre").value=current;const libraryCurrent=$("#library-genre").value;$("#library-genre").innerHTML='<option value="Všechny">Všechny žánry</option>'+all.map(g=>'<option>'+esc(g)+'</option>').join("");if(all.includes(libraryCurrent))$("#library-genre").value=libraryCurrent;$('[name="genre"]').innerHTML=all.map(g=>'<option>'+esc(g)+'</option>').join("");$('[name="genre_secondary"]').innerHTML='<option value="">Bez druhého žánru</option>'+all.map(g=>'<option>'+esc(g)+'</option>').join("")}
function updatePlatforms(){const current=$("#draw-platform").value,platforms=[...new Set(items.map(x=>x.platform).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"cs"));$("#draw-platform").innerHTML='<option value="any">Všechny platformy</option>'+platforms.map(p=>'<option>'+esc(p)+'</option>').join("");if(platforms.includes(current))$("#draw-platform").value=current}
function ownRating(x){const ratings=[x.rating_kuba,x.rating_partner].filter(v=>v!=null&&v!=="").map(Number);return ratings.length?ratings.reduce((a,b)=>a+b,0)/ratings.length:null}
function card(x){const ours=ownRating(x);const meta=x.type==="series"?[x.year,x.seasons&&x.seasons+" řad",x.platform,x.vote_average&&"TMDb ★ "+Number(x.vote_average).toFixed(1),ours&&"Naše ♥ "+ours.toFixed(1)]:[x.year,x.runtime&&x.runtime+" min",x.platform,x.vote_average&&"TMDb ★ "+Number(x.vote_average).toFixed(1),ours&&"Naše ♥ "+ours.toFixed(1)];const poster=x.poster_path?' style="background-image:linear-gradient(0deg,#111 0,transparent 65%),url(https://image.tmdb.org/t/p/w500'+esc(x.poster_path)+')"':"";return '<article class="card" data-card-id="'+x.id+'"><div class="poster p'+(String(x.id).charCodeAt(0)%5)+'"'+poster+'><span>'+(x.type==="movie"?"FILM":"SERIÁL")+' · '+esc([x.genre,x.genre_secondary].filter(Boolean).join(" · "))+'</span>'+(x.poster_path?"":'<strong>'+esc(x.title[0])+'</strong>')+'<button class="heart '+(x.favorite?"on":"")+'" data-action="favorite" data-id="'+x.id+'">♥</button></div><div class="body"><div class="title"><div><h3>'+esc(x.title)+'</h3>'+(x.original_title&&x.original_title.toLocaleLowerCase()!==x.title.toLocaleLowerCase()?'<span class="original-title">'+esc(x.original_title)+'</span>':'')+'<p>'+meta.filter(Boolean).map(esc).join(" · ")+'</p></div><button class="delete" data-action="delete" data-id="'+x.id+'">×</button></div>'+(x.overview?'<p class="overview">'+esc(x.overview)+'</p>':"")+(x.note?'<blockquote>„'+esc(x.note)+'“</blockquote>':"")+'<div class="seen-buttons"><button class="'+(x.seen_kuba?"yes":"")+'" data-action="kuba" data-id="'+x.id+'"><i>'+(x.seen_kuba?"✓":"")+'</i>Kuba</button><button class="'+(x.seen_partner?"yes":"")+'" data-action="partner" data-id="'+x.id+'"><i>'+(x.seen_partner?"✓":"")+'</i>Iry</button></div></div></article>'}
function libraryMarkup(list){if(activeType!=="movie")return '<div class="grid standalone-grid">'+list.map(card).join("")+'</div>';const grouped=new Map(),singles=[];list.forEach(x=>{if(x.collection_id){const key=String(x.collection_id);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(x)}else singles.push(x)});const collectionTotal=new Map();items.filter(x=>x.type==="movie"&&x.collection_id).forEach(x=>collectionTotal.set(String(x.collection_id),(collectionTotal.get(String(x.collection_id))||0)+1));const collections=[];for(const[key,group]of grouped){if((collectionTotal.get(key)||0)<2){singles.push(...group);continue}group.sort((a,b)=>Number(a.year||9999)-Number(b.year||9999));const first=group[0],seen=group.filter(x=>x.seen_kuba&&x.seen_partner).length,cover=first.collection_poster_path?' style="background-image:url(https://image.tmdb.org/t/p/w185'+esc(first.collection_poster_path)+')"':"";collections.push('<section class="film-collection"><button class="collection-header" data-collection-toggle type="button" aria-expanded="true"><span class="collection-cover"'+cover+'></span><span class="collection-info"><small>FILMOVÁ SÉRIE</small><h3>'+esc(first.collection_name||"Filmová série")+'</h3><span>'+group.length+' filmů · '+seen+' společně viděno</span></span><span class="collection-chevron">⌄</span></button><div class="collection-movies"><div class="grid">'+group.map(card).join("")+'</div></div></section>')}collections.sort((a,b)=>a.localeCompare(b,"cs"));return collections.join("")+'<div class="grid standalone-grid">'+singles.map(card).join("")+'</div>'}
function render(){const pool=eligible(),list=filteredLibrary(),typeItems=items.filter(x=>x.type===activeType),both=typeItems.filter(x=>x.seen_kuba&&x.seen_partner).length;$("#pool").textContent=pool.length;$("#draw").disabled=!pool.length;$(".no-match").classList.toggle("hidden",Boolean(pool.length)||!typeItems.length);$("#total").textContent=typeItems.length;$("#remaining").textContent=typeItems.length-both;$("#together").textContent=both;$("#count").textContent=list.length+" titulů";$("#items").innerHTML=libraryMarkup(list);$("#items").classList.toggle("hidden",!list.length);$("#empty").classList.toggle("hidden",Boolean(list.length));$("#library-title").textContent=activeType==="movie"?"Naše filmy":"Naše seriály";$("#draw").textContent=activeType==="movie"?"✦ Vylosovat film":"✦ Vylosovat seriál";$("#duration-label").classList.toggle("hidden",activeType==="series")}
function switchType(type){activeType=type;picked=null;drawRun++;drawInProgress=false;$("#roulette").classList.add("hidden");$("#winner").classList.add("hidden");$(".type-switch button,.collection-switch button").forEach(b=>b.classList.toggle("active",b.dataset.type===type));$(".nav-tab").forEach(b=>b.classList.toggle("active",b.dataset.view===(type==="movie"?"movies":"series")));render()}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function rouletteCard(x){const image=x.poster_path?"linear-gradient(0deg,#171416 0,transparent 58%),url(https://image.tmdb.org/t/p/w500"+esc(x.poster_path)+")":"radial-gradient(circle at 30% 20%,#9b533a,#281412 70%)";const meta=[x.year,[x.genre,x.genre_secondary].filter(Boolean).join(" · "),x.vote_average&&"★ "+Number(x.vote_average).toFixed(1)].filter(Boolean).map(esc).join(" · ");return '<div class="roulette-poster" style="background:'+image+'">'+(x.poster_path?"":'<strong>'+esc(x.title[0])+'</strong>')+'</div><div class="roulette-copy"><h2>'+esc(x.title)+'</h2><span>'+meta+'</span></div>'}
function paintRoulette(x,animate=true){const card=$("#roulette-card");card.innerHTML=rouletteCard(x);card.classList.remove("spinning");if(animate){void card.offsetWidth;card.classList.add("spinning")}}
function weightedPick(pool){const mode=$("#draw-mode").value;if(mode==="random")return pool[Math.floor(Math.random()*pool.length)];const weights=pool.map(x=>mode==="favorites"?(x.favorite?5:1):Math.max(1,ownRating(x)||Number(x.vote_average)||1)),total=weights.reduce((a,b)=>a+b,0);let hit=Math.random()*total;for(let i=0;i<pool.length;i++){hit-=weights[i];if(hit<=0)return pool[i]}return pool.at(-1)}
async function draw(overridePool=null){const pool=overridePool||eligible();if(!pool.length||drawInProgress){if(!pool.length)toast("Tomuto výběru neodpovídá žádný titul.");return}const run=++drawRun;drawInProgress=true;$("#draw").disabled=true;$("#winner").classList.add("hidden");$("#roulette").classList.remove("hidden");$(".roulette-modal").classList.remove("won");$("#roulette-actions").classList.add("hidden");$("#roulette-label").textContent="LOSOVÁNÍ…";const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const rounds=reduced?1:14;for(let i=0;i<rounds;i++){if(run!==drawRun)return;picked=weightedPick(pool);paintRoulette(picked,!reduced);if(!reduced)await wait(55+i*i*3)}if(run!==drawRun)return;drawInProgress=false;$("#draw").disabled=false;$("#roulette-label").textContent=activeType==="movie"?"DNES VEČER VYHRÁVÁ":"DNES VEČER VYHRÁVÁ";$(".roulette-modal").classList.add("won");$("#roulette-actions").classList.remove("hidden")}
function closeRoulette(){drawRun++;drawInProgress=false;$("#roulette").classList.add("hidden");$("#draw").disabled=!eligible().length}
function showWinner(){const w=$("#winner");w.classList.remove("hidden");w.innerHTML='<div><small>DNES VEČER VYHRÁVÁ</small><h2>'+esc(picked.title)+'</h2>'+(picked.original_title&&picked.original_title.toLocaleLowerCase()!==picked.title.toLocaleLowerCase()?'<span class="winner-original">'+esc(picked.original_title)+'</span>':'')+'<p>'+[picked.year,[picked.genre,picked.genre_secondary].filter(Boolean).join(" · "),picked.type==="series"?(picked.seasons?picked.seasons+" řad":null):(picked.runtime?picked.runtime+" min":null),picked.platform].filter(Boolean).map(esc).join(" · ")+'</p></div><button id="again">↻ Jiný titul</button>';$("#again").onclick=draw}
function openDetail(id){const x=items.find(i=>String(i.id)===String(id));if(!x)return;const form=$("#detail-form"),poster=x.poster_path?' style="background-image:linear-gradient(0deg,#161618,transparent),url(https://image.tmdb.org/t/p/w500'+esc(x.poster_path)+')"':"";$("#detail-hero").innerHTML='<div class="detail-backdrop"'+poster+'></div><div><small>'+(x.type==="movie"?"FILM":"SERIÁL")+'</small><h2>'+esc(x.title)+'</h2>'+(x.original_title&&x.original_title.toLowerCase()!==x.title.toLowerCase()?'<span>'+esc(x.original_title)+'</span>':'')+(x.overview?'<p>'+esc(x.overview)+'</p>':'')+'</div>';form.elements.id.value=x.id;for(const name of["title","platform","year","runtime","seasons","status","rating_kuba","rating_partner","note"])if(form.elements[name])form.elements[name].value=x[name]??"";const genres=[...new Set([...GENRES,...items.flatMap(i=>[i.genre,i.genre_secondary]).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,"cs"));form.elements.genre.innerHTML=genres.map(g=>'<option>'+esc(g)+'</option>').join("");form.elements.genre_secondary.innerHTML='<option value="">Bez druhého žánru</option>'+genres.map(g=>'<option>'+esc(g)+'</option>').join("");form.elements.genre.value=x.genre;form.elements.genre_secondary.value=x.genre_secondary||"";form.elements.seen_kuba.checked=x.seen_kuba;form.elements.seen_partner.checked=x.seen_partner;$(".detail-runtime").classList.toggle("hidden",x.type==="series");$(".detail-seasons").classList.toggle("hidden",x.type==="movie");$("#detail-modal").classList.remove("hidden")}
function closeDetail(){$("#detail-modal").classList.add("hidden")}
async function tmdbFetch(path){const response=await fetch("https://api.themoviedb.org/3"+path,{headers:{Authorization:"Bearer "+cfg.tmdbReadToken,accept:"application/json"}});if(!response.ok)throw new Error("TMDb "+response.status);return response.json()}
async function searchTmdb(query){const box=$("#tmdb-results");if(!tmdbReady||query.trim().length<2){box.classList.add("hidden");return}box.innerHTML='<div class="tmdb-loading">Vyhledávám v TMDb…</div>';box.classList.remove("hidden");try{const endpoint=$('[name="type"]:checked').value==="movie"?"movie":"tv";const data=await tmdbFetch("/search/"+endpoint+"?language=cs-CZ&include_adult=false&query="+encodeURIComponent(query));const results=(data.results||[]).slice(0,6);box.innerHTML=results.length?results.map(x=>{const title=x.title||x.name,original=x.original_title||x.original_name||"",date=x.release_date||x.first_air_date||"",img=x.poster_path?"https://image.tmdb.org/t/p/w92"+x.poster_path:"";return '<button type="button" class="tmdb-result" data-tmdb-id="'+x.id+'">'+(img?'<img src="'+img+'" alt="">':'<span></span>')+'<span><b>'+esc(title)+'</b>'+(original&&original.toLocaleLowerCase()!==title.toLocaleLowerCase()?'<span class="tmdb-original">'+esc(original)+'</span>':'')+'<span>'+esc(date.slice(0,4))+' · '+(endpoint==="movie"?"Film":"Seriál")+'</span></span></button>'}).join(""):'<div class="tmdb-loading">Nic jsme nenašli. Titul můžeš vyplnit ručně.</div>'}catch{box.innerHTML='<div class="tmdb-loading">TMDb nyní neodpovídá. Titul můžeš vyplnit ručně.</div>'}}
function setOption(name,value){if(!value)return;const select=$('[name="'+name+'"]');if(![...select.options].some(o=>o.value===value))select.add(new Option(value,value));select.value=value}
async function selectTmdb(id){const type=$('[name="type"]:checked').value;try{const endpoint=type==="movie"?"movie":"tv";const x=await tmdbFetch("/"+endpoint+"/"+id+"?language=cs-CZ");selectedTmdb=x;$('[name="title"]').value=x.title||x.name||"";$('[name="year"]').value=(x.release_date||x.first_air_date||"").slice(0,4);$('[name="runtime"]').value=type==="movie"?(x.runtime||""):"";$('[name="seasons"]').value=type==="series"?(x.number_of_seasons||""):"";$('[name="overview"]').value=x.overview||"";setOption("genre",x.genres?.[0]?.name);setOption("genre_secondary",x.genres?.[1]?.name);$("#tmdb-results").classList.add("hidden");toast("Údaje byly načteny z TMDb.")}catch{toast("Detail titulu se nepodařilo načíst.")}}
function openModal(){selectedTmdb=null;$("#modal").classList.remove("hidden");$('[name="type"][value="'+activeType+'"]').checked=true;setTimeout(()=>$('[name="title"]').focus(),50)}
function closeModal(){selectedTmdb=null;$("#modal").classList.add("hidden");$("#tmdb-results").classList.add("hidden");$("#form").reset()}
$$(".add").forEach(b=>b.onclick=openModal);$(".close").onclick=closeModal;$("#modal").onmousedown=e=>{if(e.target===e.currentTarget)closeModal()};$$(".type-switch button,.collection-switch button").forEach(b=>b.onclick=()=>switchType(b.dataset.type));$$(".nav-tab").forEach(b=>b.onclick=()=>{switchType(b.dataset.view==="movies"?"movie":"series");$("#library").scrollIntoView()});
["genre","seen","duration","draw-platform","draw-mode","library-filter","library-genre","library-sort"].forEach(id=>$("#"+id).onchange=render);$("#avoid-recent").onchange=render;$("#search").oninput=render;$("#draw").onclick=draw;$("#roulette-close").onclick=closeRoulette;$("#roulette-accept").onclick=acceptPick;$("#roulette-again").onclick=()=>{drawInProgress=false;draw()};$("#roulette").onmousedown=e=>{if(e.target===e.currentTarget&&!drawInProgress)closeRoulette()};
$('[name="title"]').oninput=e=>{selectedTmdb=null;clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchTmdb(e.target.value),300)};
$("#tmdb-results").onclick=e=>{const button=e.target.closest("[data-tmdb-id]");if(button)selectTmdb(button.dataset.tmdbId)};
$$('[name="type"]').forEach(r=>r.onchange=()=>{selectedTmdb=null;$("#tmdb-results").classList.add("hidden");$('[name="title"]').value="";$('[name="runtime"]').closest("label").classList.toggle("hidden",r.value==="series"&&r.checked);$('[name="seasons"]').closest("label").classList.toggle("hidden",r.value==="movie"&&r.checked)});
$("#form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),type=f.get("type");await createTitle({type,title:String(f.get("title")).trim(),genre:f.get("genre"),genre_secondary:f.get("genre_secondary")||null,year:f.get("year")?Number(f.get("year")):null,runtime:type==="movie"&&f.get("runtime")?Number(f.get("runtime")):null,seasons:type==="series"&&f.get("seasons")?Number(f.get("seasons")):null,platform:String(f.get("platform")||"").trim(),status:f.get("status"),overview:String(f.get("overview")||"").trim(),note:String(f.get("note")||"").trim(),seen_kuba:f.get("seen_kuba")==="on",seen_partner:f.get("seen_partner")==="on",favorite:false,tmdb_id:selectedTmdb?.id||null,original_title:selectedTmdb?.original_title||selectedTmdb?.original_name||null,poster_path:selectedTmdb?.poster_path||null,vote_average:selectedTmdb?.vote_average||null,collection_id:type==="movie"?(selectedTmdb?.belongs_to_collection?.id||null):null,collection_name:type==="movie"?(selectedTmdb?.belongs_to_collection?.name||null):null,collection_poster_path:type==="movie"?(selectedTmdb?.belongs_to_collection?.poster_path||null):null,collection_checked:type!=="movie"||Boolean(selectedTmdb)})};
$("#items").onclick=e=>{const toggle=e.target.closest("[data-collection-toggle]");if(toggle){const section=toggle.closest(".film-collection"),collapsed=section.classList.toggle("collapsed");toggle.setAttribute("aria-expanded",String(!collapsed));return}const b=e.target.closest("[data-action]");if(b){const x=items.find(i=>String(i.id)===b.dataset.id);if(!x)return;if(b.dataset.action==="delete")deleteTitle(x.id);if(b.dataset.action==="favorite")patchTitle(x.id,{favorite:!x.favorite});if(b.dataset.action==="kuba")patchTitle(x.id,{seen_kuba:!x.seen_kuba});if(b.dataset.action==="partner")patchTitle(x.id,{seen_partner:!x.seen_partner});return}const card=e.target.closest("[data-card-id]");if(card)openDetail(card.dataset.cardId)};
$(".detail-close").onclick=closeDetail;$("#detail-modal").onmousedown=e=>{if(e.target===e.currentTarget)closeDetail()};$("#detail-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get("id"),x=items.find(i=>String(i.id)===String(id));if(!x)return;await patchTitle(x.id,{title:String(f.get("title")).trim(),platform:String(f.get("platform")||"").trim(),genre:f.get("genre"),genre_secondary:f.get("genre_secondary")||null,year:f.get("year")?Number(f.get("year")):null,runtime:x.type==="movie"&&f.get("runtime")?Number(f.get("runtime")):null,seasons:x.type==="series"&&f.get("seasons")?Number(f.get("seasons")):null,status:f.get("status"),rating_kuba:f.get("rating_kuba")?Number(f.get("rating_kuba")):null,rating_partner:f.get("rating_partner")?Number(f.get("rating_partner")):null,note:String(f.get("note")||"").trim(),seen_kuba:f.get("seen_kuba")==="on",seen_partner:f.get("seen_partner")==="on"});closeDetail();toast("Změny byly uloženy.")};
$("#history-items").onclick=async e=>{const b=e.target.closest("[data-history]");if(!b)return;const h=historyItems.find(x=>String(x.id)===b.dataset.id);if(!h)return;if(b.dataset.history==="delete")removeHistory(h.id);if(b.dataset.history==="watched"){const watched=!h.watched;await updateHistory(h.id,{watched,watched_at:watched?new Date().toISOString():null});const title=items.find(x=>String(x.id)===String(h.title_id));if(title&&watched)patchTitle(title.id,{seen_kuba:true,seen_partner:true})}};
$("[data-quick]").forEach(b=>b.onclick=()=>{if(b.dataset.quick==="surprise"){switchType(activeType);$("#genre").value="Všechny";$("#seen").value="any";$("#draw-platform").value="any";$("#draw-mode").value="random";draw()}if(b.dataset.quick==="short"){switchType("movie");$("#duration").value="90";draw()}if(b.dataset.quick==="continue"){switchType("movie");const candidates=[];const groups=new Map();items.filter(x=>x.type==="movie"&&x.collection_id&&!(x.seen_kuba&&x.seen_partner)).forEach(x=>{const key=String(x.collection_id);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(x)});for(const group of groups.values())candidates.push(group.sort((a,b)=>Number(a.year||9999)-Number(b.year||9999))[0]);if(candidates.length)draw(candidates);else{switchType("series");const watching=items.filter(x=>x.type==="series"&&x.status==="watching");draw(watching)}}});
updateGenres();updatePlatforms();load();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));if(cloud){db.channel("titles-live").on("postgres_changes",{event:"*",schema:"public",table:"titles"},()=>load()).subscribe();db.channel("history-live").on("postgres_changes",{event:"*",schema:"public",table:"draw_history"},()=>loadHistory()).subscribe()}