const GENRES=["Komedie","Horor","Thriller","Drama","Sci-fi","Akční","Romantika","Animovaný","Dokument","Fantasy","Krimi"];
const cfg=window.MOVIENIGHT_CONFIG||{};const cloud=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey);const db=cloud?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
let items=[],activeType="movie",picked=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=message=>{const el=$("#toast");el.textContent=message;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),2600)};
function normalize(row){return{...row,seen_kuba:Boolean(row.seen_kuba),seen_partner:Boolean(row.seen_partner),favorite:Boolean(row.favorite)}}
async function load(){if(cloud){const{data,error}=await db.from("titles").select("*").order("created_at",{ascending:false});if(error)return toast("Nepodařilo se načíst databázi.");items=(data||[]).map(normalize)}else{items=JSON.parse(localStorage.getItem("movienight_titles")||"[]")}render()}
function saveLocal(){localStorage.setItem("movienight_titles",JSON.stringify(items))}
async function createTitle(value){if(cloud){const{data,error}=await db.from("titles").insert(value).select().single();if(error)return toast("Titul se nepodařilo uložit.");items.unshift(normalize(data))}else{items.unshift({...value,id:crypto.randomUUID(),created_at:new Date().toISOString()});saveLocal()}render();toast(value.type==="movie"?"Film byl přidán.":"Seriál byl přidán.")}
async function patchTitle(id,changes){items=items.map(x=>x.id===id?{...x,...changes}:x);render();if(cloud){const{error}=await db.from("titles").update(changes).eq("id",id);if(error){toast("Změnu se nepodařilo uložit.");load()}}else saveLocal()}
async function deleteTitle(id){if(!confirm("Opravdu odstranit titul ze seznamu?"))return;if(cloud){const{error}=await db.from("titles").delete().eq("id",id);if(error)return toast("Titul se nepodařilo odstranit.")}items=items.filter(x=>x.id!==id);saveLocal();render();toast("Titul byl odstraněn.")}
function eligible(){const genre=$("#genre").value,seen=$("#seen").value,duration=$("#duration").value;return items.filter(x=>x.type===activeType&&(genre==="Všechny"||x.genre===genre||x.genre_secondary===genre)&&(seen!=="nobody"||(!x.seen_kuba&&!x.seen_partner))&&(seen!=="kuba"||!x.seen_kuba)&&(seen!=="partner"||!x.seen_partner)&&(seen!=="not-both"||!(x.seen_kuba&&x.seen_partner))&&(activeType==="series"||duration==="any"||Number(x.runtime||999)<=Number(duration)))}
function filteredLibrary(){const q=$("#search").value.toLowerCase(),f=$("#library-filter").value;return items.filter(x=>x.type===activeType&&(x.title+" "+x.genre+" "+(x.genre_secondary||"")+" "+(x.platform||"")).toLowerCase().includes(q)&&(f!=="unseen"||!(x.seen_kuba&&x.seen_partner))&&(f!=="favorites"||x.favorite))}
function updateGenres(){const current=$("#genre").value;$("#genre").innerHTML='<option>Všechny</option>'+GENRES.map(g=>'<option>'+g+'</option>').join("");if([...$("#genre").options].some(o=>o.value===current))$("#genre").value=current;$('[name="genre"]').innerHTML=GENRES.map(g=>'<option>'+g+'</option>').join("");$('[name="genre_secondary"]').innerHTML='<option value="">Bez druhého žánru</option>'+GENRES.map(g=>'<option>'+g+'</option>').join("")}
function card(x){const meta=x.type==="series"?[x.year,x.seasons&&x.seasons+" řad",x.platform]:[x.year,x.runtime&&x.runtime+" min",x.platform];return '<article class="card"><div class="poster p'+(String(x.id).charCodeAt(0)%5)+'"><span>'+(x.type==="movie"?"FILM":"SERIÁL")+' · '+esc([x.genre,x.genre_secondary].filter(Boolean).join(' · '))+'</span><strong>'+esc(x.title[0])+'</strong><button class="heart '+(x.favorite?"on":"")+'" data-action="favorite" data-id="'+x.id+'">♥</button></div><div class="body"><div class="title"><div><h3>'+esc(x.title)+'</h3><p>'+meta.filter(Boolean).map(esc).join(" · ")+'</p></div><button class="delete" data-action="delete" data-id="'+x.id+'">×</button></div>'+(x.note?'<blockquote>„'+esc(x.note)+'“</blockquote>':'')+'<div class="seen-buttons"><button class="'+(x.seen_kuba?"yes":"")+'" data-action="kuba" data-id="'+x.id+'"><i>'+(x.seen_kuba?"✓":"")+'</i>Kuba</button><button class="'+(x.seen_partner?"yes":"")+'" data-action="partner" data-id="'+x.id+'"><i>'+(x.seen_partner?"✓":"")+'</i>Iry</button></div></div></article>'}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){const pool=eligible(),list=filteredLibrary(),typeItems=items.filter(x=>x.type===activeType),both=typeItems.filter(x=>x.seen_kuba&&x.seen_partner).length;$("#pool").textContent=pool.length;$("#draw").disabled=!pool.length;$(".no-match").classList.toggle("hidden",Boolean(pool.length)||!typeItems.length);$("#total").textContent=typeItems.length;$("#remaining").textContent=typeItems.length-both;$("#together").textContent=both;$("#count").textContent=list.length+" titulů";$("#items").innerHTML=list.map(card).join("");$("#items").classList.toggle("hidden",!list.length);$("#empty").classList.toggle("hidden",Boolean(list.length));$("#library-title").textContent=activeType==="movie"?"Naše filmy":"Naše seriály";$("#draw").textContent=activeType==="movie"?"✦ Vylosovat film":"✦ Vylosovat seriál";$("#duration-label").classList.toggle("hidden",activeType==="series")}
function switchType(type){activeType=type;picked=null;$("#winner").classList.add("hidden");$$(".type-switch button,.collection-switch button").forEach(b=>b.classList.toggle("active",b.dataset.type===type));$$(".nav-tab").forEach(b=>b.classList.toggle("active",b.dataset.view===(type==="movie"?"movies":"series")));render()}
function draw(){const pool=eligible();if(!pool.length)return;let n=0;$("#draw").disabled=true;const timer=setInterval(()=>{picked=pool[Math.floor(Math.random()*pool.length)];showWinner(true);if(++n===10){clearInterval(timer);showWinner(false);$("#draw").disabled=false}},90)}
function showWinner(rolling){const w=$("#winner");w.classList.remove("hidden");w.innerHTML='<div><small>'+(rolling?"LOSOVÁNÍ…":"DNES VEČER VYHRÁVÁ")+'</small><h2>'+esc(picked.title)+'</h2><p>'+[picked.year,[picked.genre,picked.genre_secondary].filter(Boolean).join(" · "),picked.type==="series"?(picked.seasons?picked.seasons+" řad":null):(picked.runtime?picked.runtime+" min":null),picked.platform].filter(Boolean).map(esc).join(" · ")+'</p></div>'+(rolling?"":'<button id="again">↻ Jiný titul</button>');if(!rolling)$("#again").onclick=draw}
function openModal(){const m=$("#modal");m.classList.remove("hidden");const radio=$('[name="type"][value="'+activeType+'"]');radio.checked=true;setTimeout(()=> $('[name="title"]').focus(),50)}
function closeModal(){$("#modal").classList.add("hidden");$("#form").reset()}
$$(".add").forEach(b=>b.onclick=openModal);$(".close").onclick=closeModal;$("#modal").onmousedown=e=>{if(e.target===e.currentTarget)closeModal()};$$(".type-switch button,.collection-switch button").forEach(b=>b.onclick=()=>switchType(b.dataset.type));$$(".nav-tab").forEach(b=>b.onclick=()=>{switchType(b.dataset.view==="movies"?"movie":"series");$("#library").scrollIntoView()});
["genre","seen","duration","library-filter"].forEach(id=>$("#"+id).onchange=render);$("#search").oninput=render;$("#draw").onclick=draw;
$("#form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),type=f.get("type");await createTitle({type,title:String(f.get("title")).trim(),genre:f.get("genre"),genre_secondary:f.get("genre_secondary")||null,year:f.get("year")?Number(f.get("year")):null,runtime:type==="movie"&&f.get("runtime")?Number(f.get("runtime")):null,seasons:type==="series"&&f.get("seasons")?Number(f.get("seasons")):null,platform:String(f.get("platform")||"").trim(),status:f.get("status"),note:String(f.get("note")||"").trim(),seen_kuba:f.get("seen_kuba")==="on",seen_partner:f.get("seen_partner")==="on",favorite:false});closeModal()};
$("#items").onclick=e=>{const b=e.target.closest("[data-action]");if(!b)return;const x=items.find(i=>String(i.id)===b.dataset.id);if(!x)return;if(b.dataset.action==="delete")deleteTitle(x.id);if(b.dataset.action==="favorite")patchTitle(x.id,{favorite:!x.favorite});if(b.dataset.action==="kuba")patchTitle(x.id,{seen_kuba:!x.seen_kuba});if(b.dataset.action==="partner")patchTitle(x.id,{seen_partner:!x.seen_partner})};
updateGenres();load();if(cloud)db.channel("titles-live").on("postgres_changes",{event:"*",schema:"public",table:"titles"},()=>load()).subscribe();else setTimeout(()=>toast("Lokální režim: doplňte Supabase údaje v config.js."),700);