// Veřejná konfigurace Supabase pro MovieNight.
window.MOVIENIGHT_CONFIG = {
  supabaseUrl: "https://nqvpxopsiiagemumfbmc.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xdnB4b3BzaWlhZ2VtdW1mYm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2OTQwNTcsImV4cCI6MjA5NTI3MDA1N30.VQYWGLALTxD84EksKwwUuVh5zfoAkCgenhMRXm3xdMs",
  tmdbReadToken: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0MDM4ZmQ2YWJjNDE3YmU0ZmJmYjFkNjAwMDMyYzFlMyIsIm5iZiI6MTc4NjQ0MzM0Ny4zNjksInN1YiI6IjZhN2FmNjUzY2MyYzYyYTg5MjJhM2EyMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.lt_F1b5LX_KmQ5pXCAmeAZkNhdEPzLYvkmIa6C8VaqY"
};
